### ISSUE TITLE
make `networkMap()` network-agnostic

### ISSUE THREAD

**Issue by jack-davison** [davidcarslaw/openairmaps#16]
It would be useful for `networkMap()` to display any combination of UK AQ Networks rather than one at a time. For example, those interested in air quality in Scotland may be unbothered as to whether a site is part of the AURN, SAQN or both.

Suggesting the option to do:
```
networkMap(source = c("aurn", "saqn"))
```

Which would show both networks, with a new "network" line of the popup.

Key question: how to deal with overlap (e.g., AURN sites that are also SAQN sites, with different codes used for both). Ideas:

1. Have a set hierarchy (AURN > SAQN/WAQN/NI/AQE > LMAM > KCL > EUROPE), so an AURN & SAQN site will always be labelled as an AURN site.
2. Use the provided vector order, so when `source = c("saqn", "aurn")` an AURN & SAQN site will be labelled as SAQN. This could be interpreted as "show me the SAQN, augmented with AURN sites."
3. Show both, so an AURN & SAQN site would indicate that is part of both and show both codes.

Options 1/2 are the cleanest but technically leave out information; option 3 is the most detailed but will cause issues with `control = "network"` and require a lot of refactoring. (@davidcarslaw any thoughts? Personally, leaning towards Option 2).

**Comment by davidcarslaw** [comment]
I think there is a simple priority with this as set out in (1). Number (2) seems the most practical option. It would make sense for any labelling, that in (2) it is still an AURN site that happens to be in Scotland, so perhaps labelled SAQN (AURN) or something like that. I will also think about the `openair` import functions and whether they need to be changed...

**Comment by jack-davison** [comment]
Added!

<img width="463" alt="image" src="https://user-images.githubusercontent.com/45171616/204247454-31348315-ad31-44f4-a5f1-95cae9c00a6b.png">
