### ISSUE TITLE
Possibility of using ggmap to produce static maps

### ISSUE THREAD

**Issue by mooibroekd** [davidcarslaw/openairmaps#19]
Hi @jack-davison and @davidcarslaw 

I noticed that the current versions of openairmaps revolves around leaflet maps. For publication purposes I was wondering if it would be possible to support [ggmap](https://github.com/dkahle/ggmap). I have found that exporting a leaflet map for publication in a paper requires more work compared to making a static map based on ggmap.

Best,
Dennis

**Comment by jack-davison** [comment]
Hi Dennis,

In the short term, you can turn `leaflet` maps into static images using similar code to this. Note that the zoom interface will be present at the top left, which you may have to crop out as it'd look a bit strange in a paper!

```r
# make map
map <- openairmaps::polarMap(openairmaps::polar_data, "no2")

# save map locally
htmlwidgets::saveWidget(map, "mymap.html")

# screenshot map using R
webshot2::webshot("mymap.html", "staticmap.png")
```

In terms of having proper static maps built in `{ggplot2}`, this is something I've been reflecting on. I'm almost certain it'd be simple enough to do:
- Run openair and save the plot images locally, as we do now
- Read them back in and add them as markers using, e.g., `{ggtext}` or `{ggimage}`
- If needed, create a dummy colourbar legend

A quick and dirty mockup is below if you'd like to start messing with this a bit yourself. I'll reflect on this with @davidcarslaw, but it feels like its "in scope" for `openairmaps`, so watch this space!

```r
library(openairmaps)
library(ggmap)
library(tidyverse)

plots <-
  polar_data %>%
  nest_by(lat, lon) %>%
  mutate(plot = list(
    openair::polarPlot(
      data,
      plot = FALSE,
      key = FALSE,
      limits = c(0, 500),
      par.settings = list(axis.line = list(col = "transparent"))
    )$plot
  ))

pwalk(plots, .f = ~ {
  grDevices::png(
    filename = paste0(..1, "_", ..2, ".png"),
    width = 3.5 * 300,
    height = 3.5 * 300,
    res = 300,
    bg = "transparent"
  )
  
  plot(..4)
  
  grDevices::dev.off()
})

lat_d <- abs(diff(range(plots$lat)) / 5)
minlat <- min(plots$lat) - lat_d
maxlat <- max(plots$lat) + lat_d

lon_d <- abs(diff(range(plots$lon)) / 5)
minlon <- min(plots$lon) - lon_d
maxlon <- max(plots$lon) + lon_d

map <-
  get_stamenmap(bbox = c(minlon, minlat, maxlon, maxlat),
                zoom = 14)

ggmap(map) +
  ggtext::geom_richtext(
    data = mutate(plots, url = str_glue(
      "<img src='{lat}_{lon}.png' width='150'/>"
    )),
    aes(lon, lat, label = url),
    fill = NA,
    color = NA
  ) +
  geom_point(aes(lon, lat, color = 0), alpha = 0) +
  scale_color_gradientn(limits = c(0, 500), colours = openair::openColours()) +
  labs(x = NULL, y = NULL, color = openair::quickText("NOx\n(ug/m3)"))
```

![image](https://user-images.githubusercontent.com/45171616/212293111-f2f12f96-587c-4dcc-af78-1882e6edd8c6.png)

**Comment by mooibroekd** [comment]
Yes, the way you described the second option, consisting of writing a png file, reading it back in and plotting it on the map, is exactly how I did it in my latest research paper.

I dabbled a bit with the export of leaflet, but I found it more difficult to achieve the extent of the map I needed programmatically at the time.

**Comment by jack-davison** [comment]
An early cut of this is available on the static-maps branch if folks are interested in testing.

https://github.com/davidcarslaw/openairmaps/tree/static-maps

Consider all function names, arguments, etc. subject to change!

```r
polar_data |>
  openair::cutData("weekend") |>
  ggPolarMap(
    "no2",
    alpha = .75,
    limits = c(0, 150),
    facet = "weekend",
    d.icon = 100, 
    facet.nrow = 2
  )
```

![image](https://user-images.githubusercontent.com/45171616/212556618-e98c5a7d-c561-4397-99d2-b9dc32fe392b.png)

**Comment by jack-davison** [comment]
Static maps have now been added to `openairmaps`. They are all appended with the word "Static" - e.g., `polarMap()` -> `polarMapStatic()`. Much of the same arguments are present so swapping between the two should be relatively easy (although Static doesn't have "control", "popup" or "label", and HTML doesn't have "facet").

```r
percentileMapStatic(
    polar_data,
    pollutant = "nox",
    latitude = "lat",
    longitude = "lon",
    cols = "viridis",
    intervals = c(0, 200, 400, 600, 800, 1000),
    alpha = 0.8
)
```

![image](https://user-images.githubusercontent.com/45171616/212888630-8b2a365b-24dd-421f-b7c4-6ddc026b9d7d.png)

NB: `alpha` for functions other than `polarMap()` requires a development version of openair at time of writing.

**Comment by mooibroekd** [comment]
Awesome! Thanks.

**Comment by jack-davison** [comment]
I'm sure we'd be interested in any publications you publish using it also - we're always looking for nice demonstrations of this kind of analysis/data visualization!

**Comment by mooibroekd** [comment]
> No worries, and I'm sure we'd be interested in any publications you publish using it also - we're always looking for nice demonstrations of this kind of analysis/data visualization!

I am currently looking if CBPF plots are supported, but I cannot seem to find the term CBPF in the code.

**Comment by davidcarslaw** [comment]
Hi Dennis

All the options to `polarPlot` are available in the mapping functions. So, for a CBPF plot (interactive or static), try:

```
polarMap(polar_data, pollutant = "no2", statistic = "cpf", percentile = 75)
```

or

```
polarMapStatic(polar_data, pollutant = "no2", statistic = "cpf", percentile = 75)
```

<img width="827" alt="image" src="https://user-images.githubusercontent.com/1236491/212921734-3113c403-b3bb-4186-87ab-33b7e7260548.png">
