### ISSUE TITLE
[Feature Request]: Order months in polarMapStatic

### ISSUE THREAD

**Issue by Jair-89** [davidcarslaw/openairmaps#31]
Hi!

I have an issue in the polarMapStatic, when I plot a pollutant by month, the order is not subsecuence. I try with factor, but is the same plot. I hope they can help me.

This is my sessionInfo():
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

locale:
 LC_COLLATE=Spanish_Mexico.utf8  LC_CTYPE=Spanish_Mexico.utf8    LC_MONETARY=Spanish_Mexico.utf8
LC_NUMERIC=C                    LC_TIME=Spanish_Mexico.utf8    

flextable_0.8.5     gganimate_1.0.8     gt_0.8.0            colorspace_2.1-0    RColorBrewer_1.1-3 
 ggspatial_1.1.7     rgdal_1.6-4         raster_3.6-14       sp_1.6-0            sf_1.0-9           
leaflet_2.1.1       latticeExtra_0.6-30 lattice_0.20-45     scales_1.2.1        curl_5.0.0         
jsonlite_1.8.4      httr_1.4.4          openairmaps_0.7.0   openair_2.14        lubridate_1.9.1    
 forcats_1.0.0       stringr_1.5.0       dplyr_1.1.0         purrr_1.0.1         readr_2.1.3        
 tidyr_1.3.0         tibble_3.1.8        ggplot2_3.4.1       tidyverse_1.3.2    

Regards

**Comment by jack-davison** [comment]
Hi Jair,

Thanks for bringing this to my attention! I can see this is a bug with `polarMapStatic()` and the other static polar map functions - "under the hood" factors are transformed back to unsorted characters in the `facet_wrap()` call. 

I'll work on a fix asap and let you know when its live.

Until then, you may be able to create individual polar maps and then assemble them manually using a package like [patchwork](https://patchwork.data-imaginist.com/).

Thanks,
Jack

**Comment by jack-davison** [comment]
Hi again Jair,

The fix was actually a lot easier than I expected!

Can you try installing the development version using the code below and letting me know if it is fixed?

```r
# install.packages("remotes")
remotes::install_github("davidcarslaw/openairmaps")
```

Thanks,
Jack

**Comment by Jair-89** [comment]
Hi

Thank you very much for the reply.

I was able to fix the graph.

Best regards
