### ISSUE TITLE
[Bug]: polarmap errors and warnings

### ISSUE THREAD

**Issue by mjholm4242** [davidcarslaw/openairmaps#32]
I am quite new to R but have a PhD friend helping me out.  I am getting the following messages when I run my script.
```r
> polarMap(
+         station2,
+         pollutant = "H2S",
+         latitude = "lat",
+         longitude = "lon",
+         key = TRUE
+   )
```
```r
Warning message:
There was 1 warning in `dplyr::mutate()`.
ℹ In argument: `plot = purrr::map(data, fun, .progress = "Creating Polar Markers")`.
Caused by warning:
! Returning more (or less) than 1 row per `summarise()` group was deprecated in dplyr
  1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()` always
  returns an ungrouped data frame and adjust accordingly.
ℹ The deprecated feature was likely used in the openair package.
  Please report the issue at <https://github.com/davidcarslaw/openair/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
[WARNING] Deprecated: --self-contained. use --embed-resources --standalone
[WARNING] Deprecated: --self-contained. use --embed-resources --standalone
```
It did produce a map plot but I'm wondering why I'm getting the above.
Again, I'm learning so maybe I did something wrong....

Thank you.

**Comment by jack-davison** [comment]
Hi @mjholm4242,

That is an issue to do with a recent `{dplyr}` update, which we understand to be fixed in the development version of `{openair}`. If you run the below code, ensuring you have the `{remotes}` package installed, and then re-run `polarMap()` does that sort your issue?

```r
#install.packages("remotes")
remotes::install_github("davidcarslaw/openair")
```

Jack

**Comment by mjholm4242** [comment]
I followed your instructions.  Polarmap works but I still still get the same warnings.
My friend tells me to ignore warnings for the most part.

Thanks for the help.

**Comment by jack-davison** [comment]
In that case, thanks very much for drawing our attention to this - we'll look into it!

Until then, your friend is right that the messages can be safely ignored.
