### ISSUE TITLE
[Question]: how to overlay the wind trajectory and polar map plots on the same map

### ISSUE THREAD

**Issue by gokulbalagopal** [davidcarslaw/openairmaps#35]
hi there, I recently started using openairmap. I was wondering if you had a sample code to help me overlay the wind trajectory plot and the polarmap plot on the same map. A simple example code will be very helpful. Thank you

**Comment by jack-davison** [comment]
Hi Gokul,

Is this the sort of thing you're after?

```r
library(openairmaps)
library(leaflet)

leaflet() %>%
  addTiles() %>%
  addPolarMarkers(data = polar_data,
                  fun = openair::polarPlot,
                  pollutant = "nox") %>%
  addTrajPaths(data = traj_data)
```

**Comment by gokulbalagopal** [comment]
Hi there,

Yes, that looks like exactly what I need. I tried what you shared and I got
the following error:

Error in `dplyr::mutate()`:! Problem while computing `plot =
purrr::map(data, fun, .progress = "Creating Polar  Markers")`.Caused
by error in `purrr::map()`:ℹ In index: 1.Caused by error in
`reframe()`:! could not find function "reframe"

**Comment by jack-davison** [comment]
Hi again Gokul,

I'd recommend updating your version of `{dplyr}`.

I'd also install the development version of `{openair}` using:

```r
# install.packages("remotes")
remotes::install_github("davidcarslaw/openair")
```

Then give it another go.

Best,
Jack

**Comment by gokulbalagopal** [comment]
Thanks David,
I will try that and keep you posted
