### ISSUE TITLE
increasing the size of the polar plots on the maps 

### ISSUE THREAD

**Issue by pmosn** [davidcarslaw/openairmaps#41]
Dear Jack
is there code for increasing the width and height of the polar plot itself (enlarge the polar plot not the map) on the map especially if the sites is a bit distant
Best Regards

**Comment by jack-davison** [comment]
Hi pmosn,

The `d.fig` and `d.icon` arguments control the size of the polar plots.
* `d.fig` controls the actual size of the markers.
* `d.icon` controls the resolution. This might not be relevant depending on how much you're changing `d.fig`, but it may be that if you make the markers really big you'll want to make sure the axis labels are bigger too.

Demo below using the static maps, but the args also work for the html ones too.

``` r
library(openairmaps)

polarMapStatic(polar_data, "no2", d.fig = 2, d.icon = 100)
#> ℹ Assuming latitude is 'lat'
#> ℹ Assuming longitude is 'lon'
#> Creating Polar Markers ■■■■■■■■■                         25% |  ETA:  8sCreating Polar Markers ■■■■■■■■■■■■■■■■                  50% |  ETA:  5sCreating Polar Markers ■■■■■■■■■■■■■■■■■■■■■■■           75% |  ETA:  3s                                                                         ℹ Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under ODbL.
```

![](https://i.imgur.com/RbWoya3.png)

``` r

polarMapStatic(polar_data, "no2", d.fig = 3, d.icon = 150)
#> ℹ Assuming latitude is 'lat'
#> ℹ Assuming longitude is 'lon'
#> Creating Polar Markers ■■■■■■■■■                         25% |  ETA:  4sCreating Polar Markers ■■■■■■■■■■■■■■■■                  50% |  ETA:  3sCreating Polar Markers ■■■■■■■■■■■■■■■■■■■■■■■           75% |  ETA:  1s                                                                         ℹ Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under ODbL.
```

![](https://i.imgur.com/T2nYCHl.png)

``` r

polarMapStatic(polar_data, "no2", d.fig = 4, d.icon = 200)
#> ℹ Assuming latitude is 'lat'
#> ℹ Assuming longitude is 'lon'
#> Creating Polar Markers ■■■■■■■■■                         25% |  ETA:  4sCreating Polar Markers ■■■■■■■■■■■■■■■■                  50% |  ETA:  2sCreating Polar Markers ■■■■■■■■■■■■■■■■■■■■■■■           75% |  ETA:  1s                                                                         ℹ Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under ODbL.
```

![](https://i.imgur.com/2nXOxsj.png)

<sup>Created on 2023-05-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by pmosn** [comment]
Thanks a million Jack, it really works
________________________________

**Comment by jack-davison** [comment]
Nice one, I'll close this issue then. Any more issues don't be afraid to ask 😊
