### ISSUE TITLE
save polarmap on c: 

### ISSUE THREAD

**Issue by pmosn** [davidcarslaw/openairmaps#43]
Dear Jack
is their a code that I could save  the polar map from Viewer into my pc such as partition c: without using **export-save as image function** especially I need at least 1328 width * 679 height  and the option could provide 1100 width as maximum and also I need at least 1000 dpi as resolution
I'm looking forward to hearing from you a.s.a.p.
Regards

**Comment by jack-davison** [comment]
Hi pmosn,

I think you've got two options here:

1. If you're using `polarMap()`, which creates a HTML plot, you can use a package like [webshot2](https://github.com/rstudio/webshot2) which can automatically screenshot `{leaflet}` maps.

2. As an alternative, you can use `polarMapStatic()` which will create a static version of the polar plot map in `{ggplot2}`. You can then use [`ggplot2::ggsave()`](https://ggplot2.tidyverse.org/reference/ggsave.html) to save the map output as you would any other `{ggplot2}` plot.

Hope this helps! Any more questions just let me know.

Cheers,
Jack

**Comment by jack-davison** [comment]
Hi again, 

This code:

```r
library(openairmaps)

map <- 
  polarMap(
    polar_data,
    "pm10",
    alpha = .8,
    cols = "viridis",
    provider = leaflet::providers$CartoDB.Positron
  )

htmltools::save_html(map, "temp_map.html")

webshot2::webshot(
  url = "temp_map.html",
  file = "webshot.png",
  vwidth = 1328,
  vheight = 531,
  cliprect = NULL,
  selector = NULL,
  expand = NULL,
  delay = 0.2,
  zoom = 1
)
```

Creates this image, saved at "webshot.png".

![webshot](https://github.com/davidcarslaw/openairmaps/assets/45171616/6a20cc2d-8be6-4011-b8c7-8f426713f553)

**Comment by pmosn** [comment]
Dear Jack
I did as the code, however I receive the following errors
Error trying to find path to Chrome
Error in initialize(...) : Invalid path to Chrome 
and the following is my code
library(openairmaps)

map <- 
  polarMap(
    Book1,
    "PM2.5",
    alpha = .8,
    cols = "viridis",
    provider = leaflet::providers$CartoDB.Positron
  )
htmltools::save_html(map, "temp_map.html")
webshot2::webshot(
  url = "temp_map.html",
  file = "webshot.jpeg",
  vwidth = 1328,
  vheight = 531,
  cliprect = NULL,
  selector = NULL,
  expand = NULL,
  delay = 0.2,
  zoom = 1)
What does that mean
Regards

**Comment by jack-davison** [comment]
Hi,

`{webshot2}` requires Google Chrome - do you have that installed?

If you can't install it, you could try the original [`{webshot}` package](https://wch.github.io/webshot/) which I've not used but works in a similar way. To use `{webshot}` you will need to install phantomjs (webshot has a function to do this) so you'll have to install something else regardless - either PhantomJS (webshot) or Chrome (webshot2).

Best,
Jack

**Comment by pmosn** [comment]
yes, i have google chrome

**Comment by jack-davison** [comment]
If you have chrome then I'm not sure what may be going wrong. It may be a question for the developers at https://github.com/rstudio/webshot2, especially if you can't run their webshot example:

```r
webshot2::webshot("https://www.r-project.org")
```

If that also errors, the issue is likely with webshot2 rather than openairmaps.

**Comment by pmosn** [comment]
Dear jack
Thanks a million and finally it works as there was problem with my chrome. However how can increase the resolution from 300 dpi to 1000 dpi using either webshot2 packages or gg save option
Best regards

**Comment by jack-davison** [comment]
No worries at all.

For saving HTMLs as images with {webshot2}, I think you'll have to play with zoom, vwidth and vheight: https://rstudio.github.io/webshot2/reference/webshot.html. I'm not overly familiar with doing this myself.

For saving static plots as images with ggplot2::ggsave, there is a dpi argument built-in: https://ggplot2.tidyverse.org/reference/ggsave.html

> dpi: Plot resolution. Also accepts a string input: "retina" (320), "print" (300), or "screen" (72). Applies only to raster output types.
