### ISSUE TITLE
[Question]:  a problem with adding an extra marker

### ISSUE THREAD

**Issue by pmosn** [davidcarslaw/openairmaps#50]
Dear Jack

I tried to add an extra marker to my openair maps , but the problem is when I use the following function to add refinery location as an extra function

```r
leaflet() %>%
sources <- data.frame(lat = 33.2717, lng = 44.4229, site = "Dora Refinery") %>%
polarMap(Book1, pollutant ="PM2.5", x = "ws", limits = NULL, latitude = "latitude", longitude = "longitude", control = NULL, popup = NULL, label = NULL, provider = "Esri.WorldImagery",  d.icon = 200, d.fig = 3.5, alpha = .75) %>% 
leaflet::addMarkers(data = sources, popup = ~ site, label = ~ site)
```
I receive the following error message:-
```r
Assuming "lng" and "lat" are longitude and latitude, respectively
Error in checkMapPrep(data, vars) : 
  Can't find the variable(s): PM2.5, wd, ws, latitude, longitude
```
However when I use the polarMap function alone without the %>%  pipe function, it generates the plots on map properly and the excel sheet has these variables PM2.5, wd, ws, latitude, longitude.

So, how can fix this issue and also how can I add more than one extra marker?

Finally, when I generate the CPF plots on maps how can I remove the expression (CPF at the 75th percentile (=48)) beneath the CBPF plot)

I'm looking forward to hearing from you a.s.a.p.

Best Regards
Omar Noaman

**Comment by jack-davison** [comment]
Hi Omar,

Thanks for your question; the kind of syntax we're looking for:

```r


library(openairmaps)
library(leaflet)

sources <-
  data.frame(lat = c(33.2717, 33.272),
             lng = c(44.4229, 44.5), 
             site = c("Dora Refinery", "My made up source"))

# mock up some data - you use yours!
aqdata <- openair::mydata
aqdata$lat <- 33.2
aqdata$lng <- 44.4

polarMap(
  aqdata,
  pollutant = "no2",
  statistic = "cpf",
  percentile = 75,
  sub = NULL
) %>%
  addMarkers(data = sources, popup = ~ site)
```

![image](https://github.com/davidcarslaw/openairmaps/assets/45171616/0f469ed8-edbe-4afb-9950-2f02be89cafc)

Specifics:

1. To add multiple markers you can create a bigger dataframe with more lat/lng values. Alternatively, you could just add them on one-by-one if that's more comfortable, a bit like this:

```r
polarMap(
...
) %>%
  addMarkers(lat = 1, lng = 2, popup = "x", label = "y") %>%
  addMarkers(lat = 2, lng = 3, popup = "p", label = "q") %>%
  addMarkers(lat = 4, lng = 5, popup = "s", label = "f")
```

2. The `sub = NULL` bit removes the text at the bottom of the plot. This isn't documented anywhere at the moment, so you've not missed anything!

Hope that helps,
Jack

**Comment by pmosn** [comment]
Thanks a million Jack
Problem solved
