### ISSUE TITLE
CPF probability on shared openairmap

### ISSUE THREAD

**Issue by pmosn** [davidcarslaw/openairmaps#51]
Dear Jack
when I generate a plot regarding CPF probability using openair map shared scale function, On the top of shared scale it shows the pollutant such as SO2 instead of CPF probability, while on the bottom it shows the word ((conc)) instead of the pollutant such as ((SO2)), how can I resolve the problem, by the way I use the key. Footer, and key. Header functions but it does not work it only work on openair.
I'm looking forward to hearing from you soon
Best Regards
Omar

**Comment by jack-davison** [comment]
Hi, 

So sorry for the delay in replying. Using the development version of `{openairmaps}`, you can now do:

```
polarMap(
  polar_data,
  "no2",
  statistic = "cpf",
  limits = c(0, 0.25),
  percentile = 90,
  legend.title = "CPF (NO2)"
)
```

This gives you:

![image](https://github.com/davidcarslaw/openairmaps/assets/45171616/a1ba35e4-c70e-4d0e-97fd-97411259fff7)

If you wish to control individual marker legends, `key.footer` and `key.header` still work:

```r
polarMap(
  polar_data,
  "no2",
  statistic = "cpf",
  percentile = 90,
  key = TRUE,
  key.footer = "NO2",
  key.header = "CPF"
)
```

![image](https://github.com/davidcarslaw/openairmaps/assets/45171616/2e9c975b-95e5-4ba2-b87c-78b229deeaf5)
