### ISSUE TITLE
[Bug]: Unable to run "importNOAA" function

### ISSUE THREAD

**Issue by Roset999** [davidcarslaw/openairmaps#68]
I have been accessing and downloading meteorology data from a station (931860-99999 Tauranga Airport) using this script regularly this year. getMeta(lat = -37.7, lon = 176.2) shows that data is available at this station up to 2024-05-04.
However, today the importNOAA function has not worked and produced an error as follows:

# load packages
library(tidyverse)
library(openair)
library(lubridate)
library(worldmet)

#Import recent met dataset from relevant station. 
Taurangamet2024 <- importNOAA(code = "931860-99999", year = 2023:2024)

Error:
Error in `chr_as_locations()`:                                                                                                                                             
! Can't rename columns that don't exist.
✖ Column `NAME` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.

Does this happen for anyone else? Has there been a change to the NOAA database that would cause this?

I've included the rlang::last_error()` info below:

rlang::last_error()
<error/vctrs_error_subscript_oob>
Error in `chr_as_locations()`:
! Can't rename columns that don't exist.
✖ Column `NAME` doesn't exist.
---
Backtrace:
  1. worldmet::importNOAA(code = "931860-99999", year = 2023:2024)
  2. purrr::pmap_dfr(site_process, getDat, hourly = hourly)
  3. purrr::pmap(.l, .f, ...)
  4. worldmet .f(code = .l[[1L]][[i]], year = .l[[2L]][[i]], ...)
  6. dplyr:::rename.data.frame(...)
  7. tidyselect::eval_rename(expr(c(...)), .data)
  8. tidyselect:::rename_impl(...)
  9. tidyselect:::eval_select_impl(...)
 18. tidyselect:::vars_select_eval(...)
 19. tidyselect:::walk_data_tree(expr, data_mask, context_mask, error_call)
 20. tidyselect:::eval_c(expr, data_mask, context_mask)
 21. tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 22. tidyselect:::walk_data_tree(new, data_mask, context_mask)
 23. tidyselect:::as_indices_sel_impl(...)
 24. tidyselect:::as_indices_impl(x, vars, call = call, strict = strict)
 25. tidyselect:::chr_as_locations(x, vars, call = call)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/vctrs_error_subscript_oob>
Error in `chr_as_locations()`:
! Can't rename columns that don't exist.
✖ Column `NAME` doesn't exist.
---
Backtrace:
     ▆
  1. └─worldmet::importNOAA(code = "931860-99999", year = 2023:2024)
  2.   └─purrr::pmap_dfr(site_process, getDat, hourly = hourly)
  3.     └─purrr::pmap(.l, .f, ...)
  4.       └─worldmet .f(code = .l[[1L]][[i]], year = .l[[2L]][[i]], ...)
  5.         ├─dplyr::rename(...)
  6.         └─dplyr:::rename.data.frame(...)
  7.           └─tidyselect::eval_rename(expr(c(...)), .data)
  8.             └─tidyselect:::rename_impl(...)
  9.               └─tidyselect:::eval_select_impl(...)
 10.                 ├─tidyselect:::with_subscript_errors(...)
 11.                 │ ├─base::tryCatch(...)
 12.                 │ │ └─base tryCatchList(expr, classes, parentenv, handlers)
 13.                 │ │   └─base tryCatchOne(expr, names, parentenv, handlers[[1L]])
 14.                 │ │     └─base doTryCatch(return(expr), name, parentenv, handler)
 15.                 │ └─tidyselect:::with_entraced_errors(expr)
 16.                 │   └─rlang::try_fetch(...)
 17.                 │     └─base::withCallingHandlers(...)
 18.                 └─tidyselect:::vars_select_eval(...)
 19.                   └─tidyselect:::walk_data_tree(expr, data_mask, context_mask, error_call)
 20.                     └─tidyselect:::eval_c(expr, data_mask, context_mask)
 21.                       └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 22.                         └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
 23.                           └─tidyselect:::as_indices_sel_impl(...)
 24.                             └─tidyselect:::as_indices_impl(x, vars, call = call, strict = strict)
 25.                               └─tidyselect:::chr_as_locations(x, vars, call = call)
 26.                                 └─vctrs::vec_as_location(x, n = length(vars), names = vars)
 27.                                   └─vctrs `<fn>`()
 28.                                     └─vctrs:::stop_subscript_oob(...)
 29.                                       └─vctrs:::stop_subscript(...)
 30.                                         └─rlang::abort(...)

**Comment by jack-davison** [comment]
Hi @Roset999,

This issue is related to worldmet so probably better placed in https://github.com/davidcarslaw/worldmet/issues.

I can recreate your problem, though! By the looks, the data returned by the NOAA ISD doesn't have that NAME column in it, so the code is falling over.

I am on vacation for the rest of the week, however. I don't know if @davidcarslaw has time to give it a look until then - otherwise I will when I get back.

In the short term, if you run:

```r
read.csv("https://www.ncei.noaa.gov/data/global-hourly/access/2023/93186099999.csv")
```

You'll get the raw data you need from NOAA. You can then post-process it any way you like (e.g., rename/select columns) yourself.

Cheers,
Jack

**Comment by davidcarslaw** [comment]
I just checked and it does seem that for 2024 at this site, no station NAME is supplied. That is a key bit of information. I will have to look into this and not just avoid the error as the returned data from NOAA should be in a defined and exact format.

Thanks for the report

David

**Comment by Roset999** [comment]
Hi @jack-davison and @davidcarslaw,

Thanks for the speedy response and the workaround! Unfortunately, I'm struggling a bit with the un-formatted NOAA data (not sure which part of WND denotes the wind speed, and I'm not too savvy at rearranging the date info).
Hopefully it's not too tricky/time-consuming to fix. It must be quite a recent change because I last downloaded the 2024 data on 11 March 2024 and had no issues.
Sorry for posting this in the wrong package page, I should have caught that when I pasted in the packages from my script!
Enjoy your holiday Jack :)

Thanks again,
Rose

**Comment by Roset999** [comment]
Hi @jack-davison and @davidcarslaw,

Just an update - one of my colleagues is having the same error for the Christchurch Airport station (937810-99999) when trying to access the 2024 data.
Maybe it is an NZ-wide data formatting issue rather than something station-specific?

Appreciate any help!
Cheers,
Rose

**Comment by jack-davison** [comment]
Hi Rose - thanks for updating us and trying out another site. We believe it's a global issue with all 2024 data related to a change in data format (https://github.com/davidcarslaw/worldmet/issues/33). It is possible it is related to NOAA transitioning between the Integrated Surface Database and a newer service (https://github.com/davidcarslaw/worldmet/issues/32).

The plan is to try to hotfix `{worldmet}` to work with this slightly different data format, and transition over to their new service in the longer-term.

**Comment by Roset999** [comment]
@jack-davison Hi Jack, that's all sorted for me also :)
Thanks for looking into this and for the update to let me know it's resolved!
